replicaCount: 1

image:
  repository: dragos93/argocd
  tag: "ipv-dev-0.0.1"      # ðŸ‘ˆ the exact tag you pushed
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080                # our Node app listens on 8080
